# Site settings
title: Smartjia
SEOTitle: 朱佳的博客 | smartjia's Blog
header-img: img/post-bg-desk.jpg
email: smartjia1989@163.com
description: "Every failure is leading towards success."
keyword: "smartjia's Blog, 朱佳的博客, smartjia, 朱佳, Android, Java"
url: "http://smartjia.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/smartjia/smartjia.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Goals determine what you going to be!"
sidebar-avatar: /img/smartjia.png      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
zhihu_username:     smartjia
github_username:    smartjia
jianshu_username:   4ed273c3a65d
# weibo_username:    smartjia
#facebook_username:  baiying.qiu.7
#twitter_username:   smartjia




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus settings（https://disqus.com/）
disqus_username: qiubaiying
# disqus_username: smartjia

# 多说 将于2017年6月1日正式关停服务，建议使用 Disqus（http://dev.duoshuo.com/threads/58d1169ae293b89a20c57241）
# Duoshuo settings
# duoshuo_username: qiubaiying
# Share component is depend on Comment so we can NOT use share only.
# duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68
ba_track_id: 659813f1c6818d2f0f57a9e92c2796a7

# Google Analytics

#ga_track_id: 'UA-106799869-1'           # Format: UA-xxxxxx-xx
ga_track_id: 'UA-106754600-1'            # Format: UA-xxxxxx-xx
ga_domain: smartjia.top





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "简书·smartjia",
        href: "http://www.jianshu.com/u/4ed273c3a65d"
    },
    {
        title: "高中时代",
        href: "http://www.lytjb.com/Article/ShowArticle.asp?ArticleID=424&Page=6"
    }
]
